name: Build Release Binaries

on:
  
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Single-target release
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        goos: [linux, darwin, windows]
#        goarch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install libbrotli-dev
        run: sudo apt-get update && sudo apt-get install -y libbrotli-dev

      - name: Build and release
        uses: wangyoucao577/go-release-action@v1.53
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          project_path: |
            ./cmd/ncdtree/            
